[package]
name = "eda4eda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eir = { path = "./eir" }
quote = "1.0"
syn = "2.0"
paste = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
