#!/bin/sh

# It is highly recommended to put this to your git pre-commit hook, to format your code
# before checking anything in.

# Ensure ramulator2 and wrapper are built
make test-all
if [ $? -ne 0 ]; then
    echo "Build and tests failed, please fix the issues before committing."
    exit 1
fi
