on:
  pull_request:
    branches:
      - master

name: Check and Lint

jobs:
  python:
    name: Python Lint
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install -r python/requirements.txt
      - run: pylint --rcfile python/.pylintrc python/assassyn

  fmt:
    name: Rustfmt
    runs-on: self-hosted
    container:
      image: rust:1.82
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    permissions:
      checks: write
      contents: read
    runs-on: self-hosted
    container:
      image: rust:1.82
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - run: cargo clippy -- -Dclippy::all
