on:
  pull_request:
  push:
    branches:
      - master

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install verilator
        run: |
          sudo apt-get install -y git help2man perl python3 make autoconf g++ flex bison ccache \
            libunwind-dev libgoogle-perftools-dev numactl perl-doc libfl2 libfl-dev zlib1g zlib1g-dev;
          git clone https://github.com/verilator/verilator && cd verilator && git checkout stable;
          autoconf && ./configure && make -j `nproc` && sudo make install;
      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
      - name: Generate test result
        run: |
          cargo test;
      - name: Lint the generated sv codes
        run: |
          find /tmp/*.sv -print0 | xargs -0 -n1 sh -c 'verilator --lint-only --bbox-sys --timing $0 || exit 255';
